CREATE DATABASE clouddb;

GRANT ALL PRIVILEGES
ON clouddb.*
TO 'tom'@'localhost'
IDENTIFIED BY 'password'
WITH GRANT OPTION;

GRANT ALL PRIVILEGES
ON clouddb.*
TO 'tom'@'%'
IDENTIFIED BY 'password'
WITH GRANT OPTION;

USE clouddb;

CREATE TABLE users (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMEnT,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
