version: "3"
services:
  web:
    image: tmcdonagh/websiteoverview:main
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
          ports:
            - "80:80"
